---
- name: Retrieve AWS Credentials
  hosts: localhost
  tasks:
    - name: Retrieve AWS Credentials
      set_fact:
        aws_credentials: "{{ lookup('template') }}"
      delegate_to: localhost

    - name: Use AWS Credentials
      debug:
        var: aws_credentials
