---
- name: Check Service Status on Ubuntu
  hosts: "{{ target_host }}"
  gather_facts: true

  tasks:
    - name: Get Service Status
      systemd:
        name: "{{ service_name }}"
        state: status
      register: service_status

    - name: Display Service Status
      debug:
        var: service_status
