---
- name: Get Service List on Ubuntu
  hosts: all
  gather_facts: true

  tasks:
    - name: Get Service List
      systemd:
      register: service_list

    - name: Display Service List
      debug:
        var: service_list
