---
- name: Get Service List on Ubuntu
  hosts: "{{ host }}"
  gather_facts: true

  tasks:
    - name: Get Service List
      systemd:
        state: list
      register: service_list

    - name: Display Service List
      debug:
        var: service_list
