---
- name: Get Service List on Ubuntu
  hosts: all
  gather_facts: true

  tasks:
    - name: Get Service List
      systemd:
      register: service_list

    - name: Debug Gathered Facts
      debug:
      var: ansible_facts

    - name: Debug Gathered Systemd Facts
      debug:
      var: ansible_facts.systemd

    - name: Debug Gathered Service List
      debug:
      var: service_list

