- name: Fetch SC Task Data from ServiceNow
  hosts: localhost
  gather_facts: no

  vars:
    servicenow_instance: "https://dev110810.service-now.com"
    servicenow_user: "admin"
    servicenow_password: "wO+LRiiV17*n"

  tasks:
    - name: Base64 encode credentials
      set_fact:
        encoded_credentials: "{{ (servicenow_user ~ ':' ~ servicenow_password) | b64encode }}"
      no_log: true

    - name: Fetch SC Task
      uri:
        url: "{{ servicenow_instance }}/api/now/table/sc_task"
        method: GET
        headers:
          Accept: "application/json"
          Authorization: "Basic {{ encoded_credentials | string }}"
        return_content: yes
      register: sctask_data

    - name: Print details
      debug:
        msg: "SCTask - Number: {{ item.number }}, Short Description: {{ item.short_description }}, Parent: {{ item.assignment_group.link }}"
      loop: "{{ sctask_data.json.result }}"
      loop_control:
        loop_var: item

    - name: Make API calls and get entire values
      set_fact:
        entire_values: []
      loop: "{{ sctask_data.json.result }}"
      block:
        - name: Make API call for item.request_item.link
          uri:
            url: "{{ item.request_item.link }}"
            method: GET
            headers:
              Accept: "application/json"
              Authorization: "Basic {{ encoded_credentials | string }}"
            return_content: yes
          register: item_request_item_response

        - name: Make API call for item.request.link
          uri:
            url: "{{ item.request.link }}"
            method: GET
            headers:
              Accept: "application/json"
              Authorization: "Basic {{ encoded_credentials | string }}"
            return_content: yes
          register: item_request_response

        - name: Add API responses to entire values
          set_fact:
            entire_values: "{{ entire_values + [{'sctask_data': item, 'item_request_item_response': item_request_item_response.json.result, 'item_request_response': item_request_response.json.result}] }}"

    - name: Debug Entire Values
      debug:
        var: entire_values
