- name: Fetch SC Task Data from ServiceNow
  hosts: localhost
  gather_facts: no

  vars:
    servicenow_instance: "https://dev110810.service-now.com"
    servicenow_user: "admin"
    servicenow_password: "wO+LRiiV17*n"
    entire_values: []  # Initialize empty list here to hold the API responses

  tasks:
    - name: Base64 encode credentials
      set_fact:
        encoded_credentials: "{{ (servicenow_user ~ ':' ~ servicenow_password) | b64encode }}"
      no_log: true

    - name: Fetch SC Task - Main
      block:
        - name: Fetch SC Task
          uri:
            url: "{{ servicenow_instance }}/api/now/table/sc_task"
            method: GET
            headers:
              Accept: "application/json"
              Authorization: "Basic {{ encoded_credentials | string }}"
            return_content: yes
          register: sctask_data
          failed_when: sctask_data.failed  # Fail task if unable to connect API

      rescue:
        - name: Handle Block 1 Error
          debug:
            msg: "Error occurred while fetching sctask data - {{ sctask_data.failed }}"


    - name: Filter SCTasks with open state and SCTASK number
      set_fact:
        filtered_sctasks: "{{ sctask_data.json.result | selectattr('state', 'equalto', '1') | selectattr('number', 'match', '^SCTASK') | list }}"

    - name: Fail if no suitable SCTasks found
      fail:
        msg: "No SCTask found with either open state or number not starting with SCTASK"
      when: filtered_sctasks | length == 0

    - name: Send Email on Failure
      mail:
        host: smtp.office365.com
        port: 25
        to: thiruniraiselvi.punniyakotti@capgemini.com
        subject: "Ansible Playbook Failed"
        body: "The Ansible playbook failed because no suitable SCTasks were found."
      failed_when: true  # This makes the task run only in case of failure
      always_run: yes
  
    - name: Print details
      debug:
        msg: "SCTask - Number: {{ item.number }}, Short Description: {{ item.short_description }}, Parent: {{ item.assignment_group.link }}"
      loop: "{{ sctask_data.json.result }}"
      loop_control:
        loop_var: item

    - name: Make API calls and get entire values-main
      block:
        - name: Make API calls and get entire values
          loop: "{{ filtered_sctasks }}"
          loop_control:
            loop_var: item
          include_tasks: get_api_responses.yml
          vars:
            api_encoded_credentials: "{{ encoded_credentials }}"
            item: "{{ item }}"
          when:
            - item.state == "1"
            - item.number is match("^SCTASK")
      rescue:
        - name: Handle Block 2 -Make API calls and get entire values
          debug:
            msg: "Error occurred while getting RITM and request details"
  
    - name: Change SC Task State-main
      block:
        - name: Change SC Task State
          loop: "{{ entire_values }}"
          loop_control:
            loop_var: item1
          include_tasks: sc_task_status_update.yml
          vars:
            api_encoded_credentials1: "{{ encoded_credentials }}"
            item1: "{{ item1 }}"
            servicenow_instance1: "{{ servicenow_instance }}"
          when:
            - item1.sctask_data.state == "1"
            - item1.sctask_data.number is match("^SCTASK")
      rescue:
        - name: Handle Block - SCTASK Status change
          debug:
            msg: "Error occurred while changing the SCTASK status"
    
- name: Save entire_values to CSV file
  hosts: localhost
  tasks:
    - name: Save entire_values to CSV file
      ansible.builtin.file:
        path: "{{ playbook_dir }}/api_responses.csv"
        state: touch

    - name: Write entire_values to CSV file
      ansible.builtin.copy:
        content: "{{ entire_values | to_nice_json }}"
        dest: "{{ playbook_dir }}/api_responses.csv"

    - name: Debug Variables
      debug:
        var: playbook_dir
