---
- name: Fetch SCTask details from ServiceNow
  hosts: localhost
  gather_facts: no

  vars:
    servicenow_instance: "https://dev110810.service-now.com"
    servicenow_user: "admin"
    servicenow_password: "wO+LRiiV17*n"
  
  tasks:
    - name: Base64 encode credentials
      set_fact:
        encoded_credentials: "{{ (servicenow_user ~ ':' ~ servicenow_password) | b64encode }}"
      no_log: true

    - name: Fetch SC Task
      uri:
        url: "{{ servicenow_instance }}/api/now/table/sc_task"
        method: GET
        return_content: yes
        headers:
          Accept: "application/json"
          Authorization: "Basic {{ encoded_credentials }}"
          body_format: json
        body:
          state: 1  # Open state - Change task state in ServiceNow. You may need to adjust this based on your ServiceNow instance.
      register: sctask_response

    - name: Extract SCTask sys_ids
      set_fact:
        sctask_sysids: "{{ sctask_response.json.result | map(attribute='sys_id') | list }}"

    - name: Get RITM and Request details for each SCTask
      uri:
        url: "{{ servicenow_instance }}/api/now/table/sc_task/{{ item }}"
        method: GET
        return_content: yes
        headers:
          Authorization: "Basic {{ encoded_credentials }}"
        body_format: json
      loop: "{{ sctask_sysids }}"
      register: sctask_details

    - name: Create the JSON output
      set_fact:
        sctask_details_json: "{{ sctask_details.results | map(attribute='json') | list }}"

    # Optionally, you can write the JSON output to a file
    - name: Write JSON output to a file
      copy:
        content: "{{ sctask_details_json | to_nice_json }}"
        dest: "/path/to/output_file.json"
