---
- name: Fetch SCTask details from ServiceNow
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Fetch SCTask details
      uri:
        url: "https://dev110810.service-now.com/api/now/table/sc_task"
        method: GET
        user: "admin"
        password: "wO+LRiiV17*n"
        return_content: yes
        body_format: json
        headers:
          Accept: "application/json"
      register: sctask_details

    - name: Save JSON payload to global variable
      set_fact:
        sctask_payload: "{{ sctask_details.json }}"
      
    - name: Save JSON payload to a file
      copy:
        content: "{{ sctask_details.content | to_nice_json }}"
        dest: "C:\\temp\\sctask_details.json"
		
	- name: Debug sctask_payload variable
	  debug:
        var: sctask_payload
        
