---
- name: Fetch SCTask details from ServiceNow
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Fetch SCTask details
      uri:
        url: "https://dev110810.service-now.com/api/now/table/sc_task"
        method: GET
        user: "admin"
        password: "wO+LRiiV17*n"
        return_content: yes
        body_format: json
        headers:
          Accept: "application/json"
      register: sctask_details

    - name: Save JSON payload to global variable
      set_fact:
        sctask_payload: "{{ sctask_details.json }}"
      
    - name: Create local JSON file from Jinja2 template
      template:
        src: sctask_details_template.json.j2
        dest: "/path/to/save/sctask_details.json"
      delegate_to: localhost
      run_once: true

    - name: Transfer JSON file to the remote system
      copy:
        src: "/path/to/save/sctask_details.json"
        dest: "C:/temp/sctask_details.json"

    - name: Display SCTask payload
      debug:
        var: sctask_payload
